### ISSUE TITLE
Collab

### ISSUE THREAD

**Issue by theminecoder** [BlockedServersMC/Website#1]
Hey @Chnkr was wondering if you wanted to collab and build up a database website for all of this. ;) We had the same idea name for a github org it seems too xD

**Comment by Chnkr** [comment]
No, i don't have the time to maintain a lot of projects, and especially for something silly like this. `BlockedServers/tracker` does what it needs to do, and utilizes github to maintain a proper list of changes.

**Comment by theminecoder** [comment]
Fairs :)
